travis:
  secure:
    BINSTAR_TOKEN: GGpEIjDCtEq7nw3kJo85FNZrr7P6BGvchjh4JNVSuPleXww5HV1sBz/inDQDNg8BLVE+FrBE0hE9DSLTqcZSzWrVLF+Y4+JUXuoaS6b7+GKZBm/AWV3sczY5T4enHE3GJA8agCUQKHgooHvA1WvRcUD1oIQXqhjLKdwCTbCqlu0CxnHXyKPSl3p/RFDwSsAGuIyUB/yMoxrLpQWQ65EyXUS2jTyvfZdB6Eld62iRuzsCpfFIr9Mx8PFzy1AiL2yBznrUzsMhu6917dqBnTeJHYSkJh0Wwmcbj91GGWePgyq8sxD0/j+qVHW/y2hBFo8bnN3XVOoghSro28GlQo0c68GpQS9Iy5Nxq3DNXxOGamTnbWfWWd5caei+m3+ptHWizT2L440idRc5IeHKBZxOtlWQE1ghGNNmQWJTeulTMgb0iRnA8MCw/6QpkKkohtIOufhrOxH5EdhHOBQjSG/ZGtTCEKzZFdeZwbKhlWVZ0QFItdbvT4T+LAFQptGjQVoWM2YFasVh1SA6R++UcOhFJ5lWnXnrBJl+bb8cOaS2YxH2bzM6hyvyKqdfUiZeognd4sB8p81tjIOWtYwtzx1brz1W4eClryuDLQPhHr68MmulkWoWwQmRQVmhzfq0IYZy26dQ0gOsrtsSdPXInWueqyFNW3+dHxBPXQF1ruVLuEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
